[package]
name = "noodleos"
version = "0.1.0"
edition = "2018"
authors = ["Purplefrizzel"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = { version = "0.9.8", features = ["map_physical_memory"]}
volatile = "0.2.6"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"